import { randomInt } from 'node:crypto';

/**
 * Temporary passwords for accounts created (or reset) by a super_admin. There is no email system, so
 * the password is shown ONCE to the person creating the account and handed over out-of-band; the
 * account is then forced to change it on first sign-in.
 *
 * Generated by the server, not typed by a person, so it cannot be a weak or reused password. 16
 * characters from a 56-character alphabet is about 93 bits, far beyond guessing, and `randomInt` uses
 * the system's cryptographic random source without modulo bias.
 *
 * The alphabet leaves out look-alikes (0/O, 1/l/I) so it survives being read aloud or retyped from a
 * message. It has no symbols, so it also survives being pasted through most chat tools untouched.
 */

export const TEMP_PASSWORD_ALPHABET =
  'ABCDEFGHJKLMNPQRSTUVWXYZ' + 'abcdefghijkmnpqrstuvwxyz' + '23456789';

export const TEMP_PASSWORD_LENGTH = 16;

export function generateTemporaryPassword(): string {
  let password = '';
  for (let index = 0; index < TEMP_PASSWORD_LENGTH; index += 1) {
    password += TEMP_PASSWORD_ALPHABET[randomInt(TEMP_PASSWORD_ALPHABET.length)];
  }
  return password;
}
